Auth guard & Unauth guard
wolox-training/jh-angular pull request #10
Opened 2021-06-09 22:03 UTC by miguelhenaoa

# Summary
- Created bookList component
- Added router-outlet to the auth component
- Create auth guard for 'auth' path
- Created guard for 'unauth' path
- Rename folder auth how unauth

# Trello Card
https://trello.com/c/n0Q90neS

# Screenshot
![image](https://user-images.githubusercontent.com/84401563/120912452-c46d9300-c654-11eb-9b94-e97fd94bed7e.png)

2021-06-10 17:12 UTC, ebedoyaalzate approved these changes

2021-06-10 17:12 UTC, ebedoyaalzate commented on src/app/screens/auth/auth.component.spec.ts
>    });
You could delete this file if you don't test this component

2021-06-11 20:16 UTC, CrisVega08 requested changes

2021-06-11 20:16 UTC, CrisVega08 commented on src/app/helpers/guards/unauth.guard.ts
> +    } else {
Unnecessary else remove 

 if (this._userService.loggedIn()) {     
   this._router.navigate(['auth/books']);     
    return false;    
   } 
   
   return true;

2021-06-16 16:37 UTC, CrisVega08 approved these changes

2021-06-18 14:25 UTC, merged