Shopping cart
wolox-training/jh-angular pull request #11
Opened 2021-06-10 20:49 UTC by miguelhenaoa

# Summary
- Created Shopping Cart component
- Create service to open component like modal
- Created test for shopping cart component and new methods of others components

# Trello Card
https://trello.com/c/fFS5XxSV

# Screenshot
![image](https://user-images.githubusercontent.com/84401563/121594892-466a0d00-ca03-11eb-8421-c53a4ce248b4.png)
![image](https://user-images.githubusercontent.com/84401563/121594920-4f5ade80-ca03-11eb-9d09-1cf95ede6772.png)
![image](https://user-images.githubusercontent.com/84401563/121594961-5d106400-ca03-11eb-989b-58b64a101724.png)

2021-06-11 16:02 UTC, ebedoyaalzate requested changes

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/book/book.component.html
> +  <img id="show-book" (click)="showBook()" [src]="book.image_url" alt="" class="book-cover">
add alt text

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/book/book.component.html
> +  <button id="btn-add" (click)="addBookToCart()" class="btn-add"> <span>+</span> </button>
Remember update the branches when add corrections

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/modal/modal.component.scss
> +    box-shadow: 0 0 8px 4px rgba(0, 0, 0, 0.1);
Add variable

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/modal/modal.component.html
> +        <a id="btn-shopping-cart" class="btn-close" (click)="close()"></a>
Use button

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/modal/modal.component.html
> +    <div>
This div isn't neccesary

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/components/modal/modal.component.scss
> +  background: rgba(0, 0, 0, 0.2);
Use variable

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/screens/auth/book-list/book-list.component.html
> +<app-header [books]="booksInCart" (showShoppingCartEvent)="showShoppingCart()"></app-header>
Do you really need to open the modal in the father component?

2021-06-11 16:02 UTC, ebedoyaalzate commented on src/app/screens/auth/components/shopping-cart/shopping-cart.component.ts
> +    this.data.splice(index, 1);
You could use filter in one line

2021-06-11 20:22 UTC, CrisVega08 requested changes

2021-06-11 20:22 UTC, CrisVega08 commented on package.json
> +    "@angular/material": "^12.0.3",
Why do you need angular/material?

2021-06-11 20:22 UTC, CrisVega08 commented on package.json
> +    "@angular/cdk": "^12.0.3",
Why do yo need this?

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/header/header.component.html
> +    <a id="btn-shopping-cart" class="btn btn-cart" (click)="showShoppingCart()" [matBadge]="books.length" matBadgeOverlap="true" matBadgeSize="small">
use button tag

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/header/header.component.html
> +    <a id="btn-logout" class="btn btn-logout" (click)="sessionLogout()">Logout</a>
same

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/header/header.component.scss
> +  height: 24px;
25px

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/header/header.component.scss
> +  width: 22px;
20px

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/modal/modal.component.html
> +    <div>
remove

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/modal/modal.component.scss
> +  left: 0;
I think you only need to properties (top or bottom and right or left)

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/modal/modal.component.scss
> +    visibility: inherit;
is unnecessary

2021-06-11 20:22 UTC, CrisVega08 commented on src/app/components/modal/modal.module.ts
> +
remove

2021-06-15 15:20 UTC, ebedoyaalzate approved these changes

2021-06-15 15:20 UTC, ebedoyaalzate commented on src/app/screens/auth/components/shopping-cart/shopping-cart.component.ts
> +    this.data.splice(this.data.findIndex(x => x === book), 1);
Use filter array method for more clean code.
`this.data = this.data.filter(x => x !== book);`

2021-06-16 16:38 UTC, CrisVega08 approved these changes

2021-06-18 14:34 UTC, merged