Sign up reactive forms
wolox-training/jh-angular pull request #3
Opened 2021-05-25 18:57 UTC by miguelhenaoa

# Summary
- Change FormsModule to ReactiveFormsModule
- Add validators match password
- Add validators required for all fields,  pattern for password field and password_confirm

# Trello Card
https://trello.com/c/OpIkB1oP/5-angular-reactive-forms

# Screenshot
<img width="398" alt="Captura de Pantalla 2021-05-25 a la(s) 1 42 27 p  m" src="https://user-images.githubusercontent.com/84401563/119553146-f9c6d680-bd60-11eb-9974-236812604bbb.png">
<img width="466" alt="Captura de Pantalla 2021-05-25 a la(s) 1 43 42 p  m" src="https://user-images.githubusercontent.com/84401563/119553171-00554e00-bd61-11eb-9468-c1ab4d283520.png">

2021-05-25 19:51 UTC, ebedoyaalzate requested changes

2021-05-25 19:51 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +    return result;
You could refactor this method with conditional ternary operator.

2021-05-25 19:51 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +    return result;
You could refactor this method with conditional ternary operator.

2021-05-25 19:51 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +  validateForm(control: string, form: FormGroup, validationType: string): boolean {
isControlHasError should work for this case.

2021-05-25 19:51 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +  validateForm(control: string, form: FormGroup, validationType: string): boolean {
isControlHasError should work for this case.

2021-05-27 18:04 UTC, ebedoyaalzate requested changes

2021-05-27 18:04 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.html
> +        </small>
You could refactor this part just let one small tag and get the message from ts

2021-05-27 18:04 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.html
> +      <div class="alert">
This div isn't necessary

2021-05-27 18:04 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.scss
> +}
Add empty line.

2021-05-31 16:45 UTC, ebedoyaalzate requested changes

2021-05-31 16:45 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +      }
You could refactor this if/else structure.

2021-06-01 01:52 UTC, ebedoyaalzate requested changes

2021-06-01 01:52 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.ts
> +      if (this.form.errors?.['MatchPassword']) {
Use && operator

2021-06-01 15:43 UTC, ebedoyaalzate approved these changes

2021-06-02 15:23 UTC, CrisVega08 commented on src/app/screens/sign-up/sign-up.component.ts
> +    if (this.form.valid) {
I think this conditional is unnecessary, you are validating the form before click event

2021-06-02 15:25 UTC, CrisVega08 approved these changes

2021-06-02 22:47 UTC, merged