Registration API integration
wolox-training/jh-angular pull request #4
Opened 2021-05-27 16:10 UTC by miguelhenaoa

# Summary
- Add API url to environment file
- Create user service
- Create method createUser in user.service file
- Show message 'success' in console

# Trello Card
https://trello.com/c/hO3bwS8o 

# Screenshot
<img width="1298" alt="Captura de Pantalla 2021-05-27 a la(s) 10 54 44 a  m" src="https://user-images.githubusercontent.com/84401563/119858364-0589d880-beda-11eb-85f9-8f69fe2d6156.png">

2021-05-31 16:45 UTC, ebedoyaalzate requested changes

2021-05-31 16:45 UTC, ebedoyaalzate commented on src/app/services/user.service.ts
> +  createUser(newUser: any) {
Use an interface for user.

2021-06-01 01:51 UTC, ebedoyaalzate approved these changes

2021-06-02 15:27 UTC, CrisVega08 commented on src/app/app.module.ts
> +    HttpClientModule
do you need httpClient module in all app?

2021-06-03 04:47 UTC, CrisVega08 approved these changes

2021-06-03 13:38 UTC, merged