Testing sign up
wolox-training/jh-angular pull request #5
Opened 2021-06-02 23:17 UTC by miguelhenaoa

# Summary
- Created test for this cases:
1. As I have not complete form, I cannot register.
2. An error message appears when entering an erroneous field.
3. When I enter a wrong field I can't submit the form.
4. When all the data is entered correctly, the call to the backend is made, the user is created and redirected to the login.
- Added interface SignUpResponse.
- Added route login in routing file for test.

# Trello Card
https://trello.com/c/OkezgiJ9

# Screenshot
<img width="656" alt="Captura de Pantalla 2021-06-02 a la(s) 6 12 11 p  m" src="https://user-images.githubusercontent.com/84401563/120563409-2072b600-c3ce-11eb-8ef5-c89a813d48d0.png">

2021-06-03 14:07 UTC, ebedoyaalzate requested changes

2021-06-03 14:07 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +      response = res;
this assignation it's unnecessary.

2021-06-03 14:07 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +    spyOn(userService, 'createUser').and.returnValue(of(SignUpMockResponse));
You could mock the return in the same initialization line.

2021-06-03 14:07 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +    const button = fixture.debugElement.nativeElement.querySelector('button');
You should select values by a id for more specificity. If you add another button it may failed

2021-06-03 14:07 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +    const button: HTMLElement = fixture.debugElement.nativeElement.querySelector('button');
same here.

2021-06-03 14:07 UTC, ebedoyaalzate commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +    const button: HTMLElement = fixture.debugElement.nativeElement.querySelector('button');
same here.

2021-06-03 14:39 UTC, CrisVega08 requested changes

2021-06-03 14:39 UTC, CrisVega08 commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +  it('not record when fields are empty', fakeAsync(() => {
Are you sure about fakeAsync and tick?

2021-06-03 14:39 UTC, CrisVega08 commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +describe('SignUpComponent should', () => {
```suggestion
describe('SignUpComponent', () => {
```

2021-06-03 14:39 UTC, CrisVega08 commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +  it('not record when fields are empty', fakeAsync(() => {
```suggestion
  it('Should not record when fields are empty', fakeAsync(() => {
```

2021-06-03 14:39 UTC, CrisVega08 commented on src/app/screens/sign-up/sign-up.component.spec.ts
> +  it('show message error', fakeAsync(() => {
Same

2021-06-03 19:07 UTC, ebedoyaalzate approved these changes

2021-06-10 16:31 UTC, CrisVega08 approved these changes

2021-06-10 16:51 UTC, merged