Login
wolox-training/jh-angular pull request #6
Opened 2021-06-03 22:50 UTC by miguelhenaoa

# Summary
- Create component Login
- Added validators form Login
- Change folder strucuture
- Create AuthModule to replace SignUpModule

# Trello Card
https://trello.com/c/vNTB5EhS

# Screenshot
![image](https://user-images.githubusercontent.com/84401563/120720182-43b26980-c491-11eb-856a-934672258733.png)
![image](https://user-images.githubusercontent.com/84401563/120720216-5331b280-c491-11eb-958e-e801db5582fb.png)
![image](https://user-images.githubusercontent.com/84401563/120720522-d8b56280-c491-11eb-92bc-0b3b21279a34.png)

2021-06-04 14:40 UTC, ebedoyaalzate requested changes

2021-06-04 14:40 UTC, ebedoyaalzate commented on src/app/screens/auth/sign-in/sign-in.component.scss
> +}
You can create an auth.component.scss file with this styles and change the stylesUrl of signUp and signIn components without duplicating code.

2021-06-05 00:16 UTC, ebedoyaalzate approved these changes

2021-06-10 16:42 UTC, CrisVega08 approved these changes

2021-06-10 16:53 UTC, merged