Session management & Logout
wolox-training/jh-angular pull request #7
Opened 2021-06-04 04:48 UTC by miguelhenaoa

# Summary
- Created component header
- Created route book and component book
- Add access token to LocalStorage
- Remove access token from LocalStorage

# Trello Card
https://trello.com/c/Vc3sJWQo

# Screenshot
![image](https://user-images.githubusercontent.com/84401563/120742521-a3723a00-c4bc-11eb-8073-d8c4709466d1.png)
![image](https://user-images.githubusercontent.com/84401563/120742564-bd138180-c4bc-11eb-8f2a-7568cbbc5a49.png)

2021-06-04 14:50 UTC, ebedoyaalzate requested changes

2021-06-04 14:50 UTC, ebedoyaalzate commented on src/app/components/header/header.component.html
> +<div class="header">
Use header tag

2021-06-04 14:50 UTC, ebedoyaalzate commented on src/app/screens/books/books.component.ts
> +    this.router.navigate(['auth/login']);
Is necessary logout from books component?

2021-06-08 18:12 UTC, ebedoyaalzate requested changes

2021-06-08 18:12 UTC, ebedoyaalzate commented on src/app/components/header/header.component.spec.ts
> +    expect(localStorage.getItem('ACCESS_TOKEN')).toBeNull();
Add items to localstorage before delete it, for verify the correct use.

2021-06-08 18:12 UTC, ebedoyaalzate commented on src/app/screens/auth/sign-in/sign-in.component.ts
>        console.error(error);
delete this console.log

2021-06-10 16:46 UTC, CrisVega08 requested changes

2021-06-10 16:46 UTC, CrisVega08 commented on src/app/components/header/header.component.html
> +  <a id="btn-logout" class="btn btn-logout" (click)="sessionLogout()">Logout</a>
Use btn

2021-06-10 16:46 UTC, CrisVega08 commented on src/app/components/header/header.component.scss
> +  box-shadow: 0 4px 10px 0 rgba(0,0,0,0.5);
use variable for color

2021-06-10 16:46 UTC, CrisVega08 commented on src/app/components/header/header.component.scss
> +  color: #000;
Use variable

2021-06-10 21:26 UTC, ebedoyaalzate approved these changes

2021-06-11 20:05 UTC, CrisVega08 approved these changes

2021-06-11 21:20 UTC, merged